name: Test and Build Anchor

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      SOLANA_BIN: $HOME/.local/share/solana/install/active_release/bin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Solana CLI tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-cli-v3.0.0

      - name: Install solana cli
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v3.0.0/install)"
        shell: bash

      - name: Update Path
        run: echo "$SOLANA_BIN" >> $GITHUB_PATH
        shell: bash

      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase
        shell: bash

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Anchor
        run: |
          npm i -g @coral-xyz/anchor-cli@0.31.1

      - name: Set solana target cluster to local
        run: solana config set --url http://localhost:8899
        shell: bash

      - name: Check solana config
        run: solana config get
        shell: bash

      - run: npm run anchor build
        shell: bash

      - run: npm run anchor test
        shell: bash
